# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-19 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startDate',
            field=models.DateField(),
        ),
    ]
